###############################################################################
#                                                                                                                                                          #
#                Configuration file for the SvxLink server                                                                           #
#                                                                                                                                                          #
###############################################################################

[GLOBAL]
#MODULE_PATH=/usr/lib/arm-linux-gnueabihf/svxlink
LOGIC_CORE_PATH=/usr/lib/arm-linux-gnueabihf/svxlink
LOGICS=ReflectorLogic1,ReflectorLogic2
CFG_DIR=svxlink.d
TIMESTAMP_FORMAT="%c"
CARD_SAMPLE_RATE=48000
CARD_CHANNELS=2
#LOCATION_INFO=LocationInfo
LINKS=LinkReflectors

[ReflectorLogic2]
TYPE=Reflector
#DNS_DOMAIN=example.com
HOSTS=portal.svxlink.uk
HOST_PORT=5300
HOST_PRIO=100
HOST_PRIO_INC=1
HOST_WEIGHT=10
CALLSIGN="MYCALL"
AUTH_KEY="Change this key now"
JITTER_BUFFER_DELAY=0
DEFAULT_TG=0
MONITOR_TGS=235
TG_SELECT_TIMEOUT=30
TG_SELECT_INHIBIT_TIMEOUT=0
ANNOUNCE_REMOTE_MIN_INTERVAL=300
EVENT_HANDLER=/usr/share/svxlink/events.tcl
#NODE_INFO_FILE=/etc/svxlink/node_info.json
MUTE_FIRST_TX_LOC=0
MUTE_FIRST_TX_REM=0
#TMP_MONITOR_TIMEOUT=3600
UDP_HEARTBEAT_INTERVAL=15
QSY_PENDING_TIMEOUT=15
DEFAULT_LANG=en_GB
#VERBOSE=1
[ReflectorLogic1]
TYPE=Reflector
#DNS_DOMAIN=example.com
HOSTS=portal.svxlink.uk
HOST_PORT=5300
HOST_PRIO=100
HOST_PRIO_INC=1
HOST_WEIGHT=10
CALLSIGN="MYCALL"
AUTH_KEY="Change this key now"
JITTER_BUFFER_DELAY=0
DEFAULT_TG=0
MONITOR_TGS=235
TG_SELECT_TIMEOUT=30
TG_SELECT_INHIBIT_TIMEOUT=0
ANNOUNCE_REMOTE_MIN_INTERVAL=300
EVENT_HANDLER=/usr/share/svxlink/events.tcl
#NODE_INFO_FILE=/etc/svxlink/node_info.json
MUTE_FIRST_TX_LOC=0
MUTE_FIRST_TX_REM=0
#TMP_MONITOR_TIMEOUT=3600
UDP_HEARTBEAT_INTERVAL=15
QSY_PENDING_TIMEOUT=15
DEFAULT_LANG=en_GB
#VERBOSE=1

[LinkToReflector]
CONNECT_LOGICS=ReflectorLogic1,ReflectorLogic2
DEFAULT_ACTIVE=1
OPTIONS = DEFAULT_CONNECT,NO_DISCONNECT
TIMEOUT=300
#ACTIVATE_ON_ACTIVITY=RepeaterLogic

